package com.zdv.renrensong.renrensong;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REN_REN_SONG_CONTENT_INFO".
 */
public class RenRenSongContentInfo {

    private Long id;
    private String order_num;
    private String order_id;
    private String sender_id;
    private String organ_id;
    private String g_time;
    private String end_time;
    private String status;
    private String item_name;
    private String item_type;
    private String item_total;
    private String item_weight;
    private String item_volume;
    private String y_address;
    private String y_tel;
    private String y_name;
    private String h_address;
    private String h_tel;
    private String h_name;
    private String create_time;
    private String finish_time;
    private String r_status;
    private String s_status;
    private String is_close;
    private String is_back;
    private String is_inventory;
    private String receiver_id;
    private String money;
    private String pay_status;
    private String c_type;
    private String gathering_num;
    private String pay_type;
    private String order_type;
    private String remark;
    private String s_id;
    private String url;
    private String distance;
    private Boolean isShow;
    private Boolean isOperating;
    private Integer activity_page;
    private String order_owner;

    public RenRenSongContentInfo() {
    }

    public RenRenSongContentInfo(Long id) {
        this.id = id;
    }

    public RenRenSongContentInfo(Long id, String order_num, String order_id, String sender_id, String organ_id, String g_time, String end_time, String status, String item_name, String item_type, String item_total, String item_weight, String item_volume, String y_address, String y_tel, String y_name, String h_address, String h_tel, String h_name, String create_time, String finish_time, String r_status, String s_status, String is_close, String is_back, String is_inventory, String receiver_id, String money, String pay_status, String c_type, String gathering_num, String pay_type, String order_type, String remark, String s_id, String url, String distance, Boolean isShow, Boolean isOperating, Integer activity_page, String order_owner) {
        this.id = id;
        this.order_num = order_num;
        this.order_id = order_id;
        this.sender_id = sender_id;
        this.organ_id = organ_id;
        this.g_time = g_time;
        this.end_time = end_time;
        this.status = status;
        this.item_name = item_name;
        this.item_type = item_type;
        this.item_total = item_total;
        this.item_weight = item_weight;
        this.item_volume = item_volume;
        this.y_address = y_address;
        this.y_tel = y_tel;
        this.y_name = y_name;
        this.h_address = h_address;
        this.h_tel = h_tel;
        this.h_name = h_name;
        this.create_time = create_time;
        this.finish_time = finish_time;
        this.r_status = r_status;
        this.s_status = s_status;
        this.is_close = is_close;
        this.is_back = is_back;
        this.is_inventory = is_inventory;
        this.receiver_id = receiver_id;
        this.money = money;
        this.pay_status = pay_status;
        this.c_type = c_type;
        this.gathering_num = gathering_num;
        this.pay_type = pay_type;
        this.order_type = order_type;
        this.remark = remark;
        this.s_id = s_id;
        this.url = url;
        this.distance = distance;
        this.isShow = isShow;
        this.isOperating = isOperating;
        this.activity_page = activity_page;
        this.order_owner = order_owner;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrder_num() {
        return order_num;
    }

    public void setOrder_num(String order_num) {
        this.order_num = order_num;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getSender_id() {
        return sender_id;
    }

    public void setSender_id(String sender_id) {
        this.sender_id = sender_id;
    }

    public String getOrgan_id() {
        return organ_id;
    }

    public void setOrgan_id(String organ_id) {
        this.organ_id = organ_id;
    }

    public String getG_time() {
        return g_time;
    }

    public void setG_time(String g_time) {
        this.g_time = g_time;
    }

    public String getEnd_time() {
        return end_time;
    }

    public void setEnd_time(String end_time) {
        this.end_time = end_time;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getItem_name() {
        return item_name;
    }

    public void setItem_name(String item_name) {
        this.item_name = item_name;
    }

    public String getItem_type() {
        return item_type;
    }

    public void setItem_type(String item_type) {
        this.item_type = item_type;
    }

    public String getItem_total() {
        return item_total;
    }

    public void setItem_total(String item_total) {
        this.item_total = item_total;
    }

    public String getItem_weight() {
        return item_weight;
    }

    public void setItem_weight(String item_weight) {
        this.item_weight = item_weight;
    }

    public String getItem_volume() {
        return item_volume;
    }

    public void setItem_volume(String item_volume) {
        this.item_volume = item_volume;
    }

    public String getY_address() {
        return y_address;
    }

    public void setY_address(String y_address) {
        this.y_address = y_address;
    }

    public String getY_tel() {
        return y_tel;
    }

    public void setY_tel(String y_tel) {
        this.y_tel = y_tel;
    }

    public String getY_name() {
        return y_name;
    }

    public void setY_name(String y_name) {
        this.y_name = y_name;
    }

    public String getH_address() {
        return h_address;
    }

    public void setH_address(String h_address) {
        this.h_address = h_address;
    }

    public String getH_tel() {
        return h_tel;
    }

    public void setH_tel(String h_tel) {
        this.h_tel = h_tel;
    }

    public String getH_name() {
        return h_name;
    }

    public void setH_name(String h_name) {
        this.h_name = h_name;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getFinish_time() {
        return finish_time;
    }

    public void setFinish_time(String finish_time) {
        this.finish_time = finish_time;
    }

    public String getR_status() {
        return r_status;
    }

    public void setR_status(String r_status) {
        this.r_status = r_status;
    }

    public String getS_status() {
        return s_status;
    }

    public void setS_status(String s_status) {
        this.s_status = s_status;
    }

    public String getIs_close() {
        return is_close;
    }

    public void setIs_close(String is_close) {
        this.is_close = is_close;
    }

    public String getIs_back() {
        return is_back;
    }

    public void setIs_back(String is_back) {
        this.is_back = is_back;
    }

    public String getIs_inventory() {
        return is_inventory;
    }

    public void setIs_inventory(String is_inventory) {
        this.is_inventory = is_inventory;
    }

    public String getReceiver_id() {
        return receiver_id;
    }

    public void setReceiver_id(String receiver_id) {
        this.receiver_id = receiver_id;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }

    public String getPay_status() {
        return pay_status;
    }

    public void setPay_status(String pay_status) {
        this.pay_status = pay_status;
    }

    public String getC_type() {
        return c_type;
    }

    public void setC_type(String c_type) {
        this.c_type = c_type;
    }

    public String getGathering_num() {
        return gathering_num;
    }

    public void setGathering_num(String gathering_num) {
        this.gathering_num = gathering_num;
    }

    public String getPay_type() {
        return pay_type;
    }

    public void setPay_type(String pay_type) {
        this.pay_type = pay_type;
    }

    public String getOrder_type() {
        return order_type;
    }

    public void setOrder_type(String order_type) {
        this.order_type = order_type;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getS_id() {
        return s_id;
    }

    public void setS_id(String s_id) {
        this.s_id = s_id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public Boolean getIsShow() {
        return isShow;
    }

    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    public Boolean getIsOperating() {
        return isOperating;
    }

    public void setIsOperating(Boolean isOperating) {
        this.isOperating = isOperating;
    }

    public Integer getActivity_page() {
        return activity_page;
    }

    public void setActivity_page(Integer activity_page) {
        this.activity_page = activity_page;
    }

    public String getOrder_owner() {
        return order_owner;
    }

    public void setOrder_owner(String order_owner) {
        this.order_owner = order_owner;
    }

}
