package com.zdv.renrensong.renrensong.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zdv.renrensong.renrensong.RenRenSongEvaluateInfo;
import com.zdv.renrensong.renrensong.RenRenSongContentInfo;

import com.zdv.renrensong.renrensong.dao.RenRenSongEvaluateInfoDao;
import com.zdv.renrensong.renrensong.dao.RenRenSongContentInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig renRenSongEvaluateInfoDaoConfig;
    private final DaoConfig renRenSongContentInfoDaoConfig;

    private final RenRenSongEvaluateInfoDao renRenSongEvaluateInfoDao;
    private final RenRenSongContentInfoDao renRenSongContentInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        renRenSongEvaluateInfoDaoConfig = daoConfigMap.get(RenRenSongEvaluateInfoDao.class).clone();
        renRenSongEvaluateInfoDaoConfig.initIdentityScope(type);

        renRenSongContentInfoDaoConfig = daoConfigMap.get(RenRenSongContentInfoDao.class).clone();
        renRenSongContentInfoDaoConfig.initIdentityScope(type);

        renRenSongEvaluateInfoDao = new RenRenSongEvaluateInfoDao(renRenSongEvaluateInfoDaoConfig, this);
        renRenSongContentInfoDao = new RenRenSongContentInfoDao(renRenSongContentInfoDaoConfig, this);

        registerDao(RenRenSongEvaluateInfo.class, renRenSongEvaluateInfoDao);
        registerDao(RenRenSongContentInfo.class, renRenSongContentInfoDao);
    }
    
    public void clear() {
        renRenSongEvaluateInfoDaoConfig.getIdentityScope().clear();
        renRenSongContentInfoDaoConfig.getIdentityScope().clear();
    }

    public RenRenSongEvaluateInfoDao getRenRenSongEvaluateInfoDao() {
        return renRenSongEvaluateInfoDao;
    }

    public RenRenSongContentInfoDao getRenRenSongContentInfoDao() {
        return renRenSongContentInfoDao;
    }

}
